_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: false
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 30
smtp_username: vladyslav.p014@gmail.com
smtp_password: 'nvod ffnf mhfz frxq'
smtp_from: vladyslav.p014@gmail.com
smtp_fromname: helper
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: helper.drupal.project@gmail.com
smtp_reroute_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: false
