_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: e96ac96f-39d0-4370-8ae1-301bb572da7d
name: 'ECA Commerce'
mail: admin@admin.com
slogan: ''
page:
  403: ''
  404: ''
  front: /admin/commerce/products
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
